serial_port: "/dev/ttyUSB0"
#serial_port: /dev/serial3by-id/usb-FTDI_FT232R_USB_UART_AB0LYXFN-if00-port0
serial_baud_rate: 115200

#    default                       example_1 
#     FRONT                          FRONT          
#    _2___1_                        _14__2_         
# 3 |       | 8                  9 |       | 5     
#   |       |                      |       |        
# 4 |       | 7                  4 |       | 1      
#    -------                        -------         
#   5      6                       5      12         
#     BACK                           BACK     
# Valid index (1~20) depends on the configuration
sonar_remapper: [1] # only one sensor
# sonar_remapper: [1,2,3,4,5,6,7,8] # default
# sonar_remapper: [2,14,9,4,5,12,1,5] # example_1

# detection_mode: 
#   0 - normal speed read (0.03m ~ 5.6m)
#   1 - high speed read (0.01m ~ 1.1m) # recommended
detection_mode: 1